/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {BrandContext, BrandModuleInput, BrandModuleOutput, BrandModuleSection, BuyerPersona, ColorSpec, ComponentContext, ComponentModuleOutput, ComponentVariant, CustomerPersonasOutput, GeometryOutput, GeometrySpec, LogoVariation, PatternSpec, PersonalityProfile, TemplateContext, TemplateField, TemplateOutput, TextContext, TextModuleOutput, VisualContext, VisualModuleOutput} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  GenerateBrandModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.BrandModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateBrandModule",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.BrandModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateComponentModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.ComponentModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateComponentModule",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ComponentModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateCustomerPersonas(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.CustomerPersonasOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateCustomerPersonas",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.CustomerPersonasOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateGeometryAuto(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.GeometryOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateGeometryAuto",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.GeometryOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateGeometryWithQuestions(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.GeometryOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateGeometryWithQuestions",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.GeometryOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateTemplateModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.TemplateOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateTemplateModule",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.TemplateOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateText(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): string {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateText",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateTextModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.TextModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateTextModule",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.TextModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateVisualModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): types.VisualModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateVisualModule",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.VisualModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  GenerateBrandModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.BrandModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateBrandModule",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.BrandModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateComponentModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.ComponentModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateComponentModule",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ComponentModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateCustomerPersonas(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.CustomerPersonasOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateCustomerPersonas",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.CustomerPersonasOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateGeometryAuto(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.GeometryOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateGeometryAuto",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.GeometryOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateGeometryWithQuestions(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.GeometryOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateGeometryWithQuestions",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.GeometryOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateTemplateModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.TemplateOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateTemplateModule",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.TemplateOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateText(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): string {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateText",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateTextModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.TextModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateTextModule",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.TextModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateVisualModule(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry, env?: Record<string, string | undefined> }
  ): partial_types.VisualModuleOutput {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.parseLlmResponse(
        "GenerateVisualModule",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.VisualModuleOutput
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}