/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  BrandContext,  BrandModuleInput,  BrandModuleOutput,  BrandModuleSection,  BuyerPersona,  ColorSpec,  ComponentContext,  ComponentModuleOutput,  ComponentVariant,  CustomerPersonasOutput,  GeometryOutput,  GeometrySpec,  LogoVariation,  PatternSpec,  PersonalityProfile,  TemplateContext,  TemplateField,  TemplateOutput,  TextContext,  TextModuleOutput,  VisualContext,  VisualModuleOutput } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BrandContext {
      name?: string | null
      personality_id?: string | null
      industry?: string | null
      offering?: string | null
    }
    export interface BrandModuleInput {
      module_key?: string | null
      module_name?: string | null
      brand_context?: BrandContext | null
      personality_profile?: PersonalityProfile | null
      user_answers: Record<string, string>
    }
    export interface BrandModuleOutput {
      title?: string | null
      description?: string | null
      body?: string | null
      sections: BrandModuleSection[]
    }
    export interface BrandModuleSection {
      heading?: string | null
      content?: string | null
      examples: string[]
    }
    export interface BuyerPersona {
      name?: string | null
      role?: string | null
      age?: string | null
      location?: string | null
      income?: string | null
      goals?: string | null
      pain_points?: string | null
      motivations?: string | null
      objections?: string | null
      quote?: string | null
    }
    export interface ColorSpec {
      hex?: string | null
      rgb?: string | null
      name?: string | null
      usage?: string | null
    }
    export interface ComponentContext {
      component_key?: string | null
      component_name?: string | null
      brand_context?: BrandContext | null
      personality_profile?: PersonalityProfile | null
      design_tokens: Record<string, string>
    }
    export interface ComponentModuleOutput {
      component_name?: string | null
      description?: string | null
      anatomy?: string | null
      variants: ComponentVariant[]
      states: string[]
      accessibility_guidelines: string[]
      code_example?: string | null
    }
    export interface ComponentVariant {
      name?: string | null
      description?: string | null
      use_case?: string | null
      properties: Record<string, string>
    }
    export interface CustomerPersonasOutput {
      title?: string | null
      personas: BuyerPersona[]
      ideal_client_suggestions: string[]
      acquisition_channels: string[]
    }
    export interface GeometryOutput {
      title?: string | null
      description?: string | null
      base_shapes: GeometrySpec[]
      patterns: PatternSpec[]
      dos: string[]
      donts: string[]
      guidelines: string[]
    }
    export interface GeometrySpec {
      shape_type?: string | null
      description?: string | null
      usage?: string | null
      color?: string | null
    }
    export interface LogoVariation {
      type?: string | null
      description?: string | null
      use_case?: string | null
    }
    export interface PatternSpec {
      name?: string | null
      description?: string | null
      style?: string | null
    }
    export interface PersonalityProfile {
      id?: string | null
      name?: string | null
      archetype?: string | null
      tagline?: string | null
      philosophy?: string | null
      key_principles: string[]
      dna?: string | null
    }
    export interface TemplateContext {
      template_key?: string | null
      template_name?: string | null
      template_type?: string | null
      brand_context?: BrandContext | null
      personality_profile?: PersonalityProfile | null
      user_answers: Record<string, string>
    }
    export interface TemplateField {
      field_name?: string | null
      field_type?: string | null
      description?: string | null
      required?: boolean | null
    }
    export interface TemplateOutput {
      template_name?: string | null
      description?: string | null
      use_cases: string[]
      structure?: string | null
      fields: TemplateField[]
      example_content?: string | null
      customization_guidelines: string[]
    }
    export interface TextContext {
      module_key?: string | null
      module_name?: string | null
      brand_context?: BrandContext | null
      personality_profile?: PersonalityProfile | null
      user_answers: Record<string, string>
      tone_profile?: string | null
    }
    export interface TextModuleOutput {
      title?: string | null
      content?: string | null
      variations: string[]
      examples: string[]
      guidelines: string[]
    }
    export interface VisualContext {
      module_key?: string | null
      module_name?: string | null
      brand_context?: BrandContext | null
      personality_profile?: PersonalityProfile | null
      user_answers: Record<string, string>
      visual_style?: string | null
      generation_mode?: string | null
    }
    export interface VisualModuleOutput {
      title?: string | null
      description?: string | null
      specifications: Record<string, string>
      colors: ColorSpec[]
      variations: LogoVariation[]
      dos: string[]
      donts: string[]
      examples: string[]
    }
}