/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface BrandContext {
  name: string
  personality_id: string
  industry: string
  offering: string
  
}

export interface BrandModuleInput {
  module_key: string
  module_name: string
  brand_context: BrandContext
  personality_profile: PersonalityProfile
  user_answers: Record<string, string>
  
}

export interface BrandModuleOutput {
  title: string
  description: string
  body: string
  sections: BrandModuleSection[]
  
}

export interface BrandModuleSection {
  heading: string
  content: string
  examples: string[]
  
}

export interface BuyerPersona {
  name: string
  role: string
  age: string
  location: string
  income: string
  goals: string
  pain_points: string
  motivations: string
  objections: string
  quote: string
  
}

export interface ColorSpec {
  hex: string
  rgb: string
  name: string
  usage: string
  
}

export interface ComponentContext {
  component_key: string
  component_name: string
  brand_context: BrandContext
  personality_profile: PersonalityProfile
  design_tokens: Record<string, string>
  
}

export interface ComponentModuleOutput {
  component_name: string
  description: string
  anatomy: string
  variants: ComponentVariant[]
  states: string[]
  accessibility_guidelines: string[]
  code_example: string
  
}

export interface ComponentVariant {
  name: string
  description: string
  use_case: string
  properties: Record<string, string>
  
}

export interface CustomerPersonasOutput {
  title: string
  personas: BuyerPersona[]
  ideal_client_suggestions: string[]
  acquisition_channels: string[]
  
}

export interface GeometryOutput {
  title: string
  description: string
  base_shapes: GeometrySpec[]
  patterns: PatternSpec[]
  dos: string[]
  donts: string[]
  guidelines: string[]
  
}

export interface GeometrySpec {
  shape_type: string
  description: string
  usage: string
  color: string
  
}

export interface LogoVariation {
  type: string
  description: string
  use_case: string
  
}

export interface PatternSpec {
  name: string
  description: string
  style: string
  
}

export interface PersonalityProfile {
  id: string
  name: string
  archetype: string
  tagline: string
  philosophy: string
  key_principles: string[]
  dna: string
  
}

export interface TemplateContext {
  template_key: string
  template_name: string
  template_type: string
  brand_context: BrandContext
  personality_profile: PersonalityProfile
  user_answers: Record<string, string>
  
}

export interface TemplateField {
  field_name: string
  field_type: string
  description: string
  required: boolean
  
}

export interface TemplateOutput {
  template_name: string
  description: string
  use_cases: string[]
  structure: string
  fields: TemplateField[]
  example_content: string
  customization_guidelines: string[]
  
}

export interface TextContext {
  module_key: string
  module_name: string
  brand_context: BrandContext
  personality_profile: PersonalityProfile
  user_answers: Record<string, string>
  tone_profile: string
  
}

export interface TextModuleOutput {
  title: string
  content: string
  variations: string[]
  examples: string[]
  guidelines: string[]
  
}

export interface VisualContext {
  module_key: string
  module_name: string
  brand_context: BrandContext
  personality_profile: PersonalityProfile
  user_answers: Record<string, string>
  visual_style: string
  generation_mode: string
  
}

export interface VisualModuleOutput {
  title: string
  description: string
  specifications: Record<string, string>
  colors: ColorSpec[]
  variations: LogoVariation[]
  dos: string[]
  donts: string[]
  examples: string[]
  
}
