/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    BrandContext: ClassViewer<'BrandContext', "name" | "personality_id" | "industry" | "offering">;
    
    BrandModuleInput: ClassViewer<'BrandModuleInput', "module_key" | "module_name" | "brand_context" | "personality_profile" | "user_answers">;
    
    BrandModuleOutput: ClassViewer<'BrandModuleOutput', "title" | "description" | "body" | "sections">;
    
    BrandModuleSection: ClassViewer<'BrandModuleSection', "heading" | "content" | "examples">;
    
    BuyerPersona: ClassViewer<'BuyerPersona', "name" | "role" | "age" | "location" | "income" | "goals" | "pain_points" | "motivations" | "objections" | "quote">;
    
    ColorSpec: ClassViewer<'ColorSpec', "hex" | "rgb" | "name" | "usage">;
    
    ComponentContext: ClassViewer<'ComponentContext', "component_key" | "component_name" | "brand_context" | "personality_profile" | "design_tokens">;
    
    ComponentModuleOutput: ClassViewer<'ComponentModuleOutput', "component_name" | "description" | "anatomy" | "variants" | "states" | "accessibility_guidelines" | "code_example">;
    
    ComponentVariant: ClassViewer<'ComponentVariant', "name" | "description" | "use_case" | "properties">;
    
    CustomerPersonasOutput: ClassViewer<'CustomerPersonasOutput', "title" | "personas" | "ideal_client_suggestions" | "acquisition_channels">;
    
    GeometryOutput: ClassViewer<'GeometryOutput', "title" | "description" | "base_shapes" | "patterns" | "dos" | "donts" | "guidelines">;
    
    GeometrySpec: ClassViewer<'GeometrySpec', "shape_type" | "description" | "usage" | "color">;
    
    LogoVariation: ClassViewer<'LogoVariation', "type" | "description" | "use_case">;
    
    PatternSpec: ClassViewer<'PatternSpec', "name" | "description" | "style">;
    
    PersonalityProfile: ClassViewer<'PersonalityProfile', "id" | "name" | "archetype" | "tagline" | "philosophy" | "key_principles" | "dna">;
    
    TemplateContext: ClassViewer<'TemplateContext', "template_key" | "template_name" | "template_type" | "brand_context" | "personality_profile" | "user_answers">;
    
    TemplateField: ClassViewer<'TemplateField', "field_name" | "field_type" | "description" | "required">;
    
    TemplateOutput: ClassViewer<'TemplateOutput', "template_name" | "description" | "use_cases" | "structure" | "fields" | "example_content" | "customization_guidelines">;
    
    TextContext: ClassViewer<'TextContext', "module_key" | "module_name" | "brand_context" | "personality_profile" | "user_answers" | "tone_profile">;
    
    TextModuleOutput: ClassViewer<'TextModuleOutput', "title" | "content" | "variations" | "examples" | "guidelines">;
    
    VisualContext: ClassViewer<'VisualContext', "module_key" | "module_name" | "brand_context" | "personality_profile" | "user_answers" | "visual_style" | "generation_mode">;
    
    VisualModuleOutput: ClassViewer<'VisualModuleOutput', "title" | "description" | "specifications" | "colors" | "variations" | "dos" | "donts" | "examples">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "BrandContext","BrandModuleInput","BrandModuleOutput","BrandModuleSection","BuyerPersona","ColorSpec","ComponentContext","ComponentModuleOutput","ComponentVariant","CustomerPersonasOutput","GeometryOutput","GeometrySpec","LogoVariation","PatternSpec","PersonalityProfile","TemplateContext","TemplateField","TemplateOutput","TextContext","TextModuleOutput","VisualContext","VisualModuleOutput",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.BrandContext = this.tb.classViewer("BrandContext", [
          "name","personality_id","industry","offering",
        ]);
        
        this.BrandModuleInput = this.tb.classViewer("BrandModuleInput", [
          "module_key","module_name","brand_context","personality_profile","user_answers",
        ]);
        
        this.BrandModuleOutput = this.tb.classViewer("BrandModuleOutput", [
          "title","description","body","sections",
        ]);
        
        this.BrandModuleSection = this.tb.classViewer("BrandModuleSection", [
          "heading","content","examples",
        ]);
        
        this.BuyerPersona = this.tb.classViewer("BuyerPersona", [
          "name","role","age","location","income","goals","pain_points","motivations","objections","quote",
        ]);
        
        this.ColorSpec = this.tb.classViewer("ColorSpec", [
          "hex","rgb","name","usage",
        ]);
        
        this.ComponentContext = this.tb.classViewer("ComponentContext", [
          "component_key","component_name","brand_context","personality_profile","design_tokens",
        ]);
        
        this.ComponentModuleOutput = this.tb.classViewer("ComponentModuleOutput", [
          "component_name","description","anatomy","variants","states","accessibility_guidelines","code_example",
        ]);
        
        this.ComponentVariant = this.tb.classViewer("ComponentVariant", [
          "name","description","use_case","properties",
        ]);
        
        this.CustomerPersonasOutput = this.tb.classViewer("CustomerPersonasOutput", [
          "title","personas","ideal_client_suggestions","acquisition_channels",
        ]);
        
        this.GeometryOutput = this.tb.classViewer("GeometryOutput", [
          "title","description","base_shapes","patterns","dos","donts","guidelines",
        ]);
        
        this.GeometrySpec = this.tb.classViewer("GeometrySpec", [
          "shape_type","description","usage","color",
        ]);
        
        this.LogoVariation = this.tb.classViewer("LogoVariation", [
          "type","description","use_case",
        ]);
        
        this.PatternSpec = this.tb.classViewer("PatternSpec", [
          "name","description","style",
        ]);
        
        this.PersonalityProfile = this.tb.classViewer("PersonalityProfile", [
          "id","name","archetype","tagline","philosophy","key_principles","dna",
        ]);
        
        this.TemplateContext = this.tb.classViewer("TemplateContext", [
          "template_key","template_name","template_type","brand_context","personality_profile","user_answers",
        ]);
        
        this.TemplateField = this.tb.classViewer("TemplateField", [
          "field_name","field_type","description","required",
        ]);
        
        this.TemplateOutput = this.tb.classViewer("TemplateOutput", [
          "template_name","description","use_cases","structure","fields","example_content","customization_guidelines",
        ]);
        
        this.TextContext = this.tb.classViewer("TextContext", [
          "module_key","module_name","brand_context","personality_profile","user_answers","tone_profile",
        ]);
        
        this.TextModuleOutput = this.tb.classViewer("TextModuleOutput", [
          "title","content","variations","examples","guidelines",
        ]);
        
        this.VisualContext = this.tb.classViewer("VisualContext", [
          "module_key","module_name","brand_context","personality_profile","user_answers","visual_style","generation_mode",
        ]);
        
        this.VisualModuleOutput = this.tb.classViewer("VisualModuleOutput", [
          "title","description","specifications","colors","variations","dos","donts","examples",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}